- Editor/Manifest.meta
- Editor/Manifest/Dependency.cs
- Editor/Manifest/Dependency.cs.meta
- Editor/Manifest/Manifest.cs
- Editor/Manifest/Manifest.cs.meta
- Editor/Manifest/ScopeRegistry.cs
- Editor/Manifest/ScopeRegistry.cs.meta
- Runtime/Utilities/MiniJSON.cs
- Runtime/Utilities/MiniJSON.cs.meta
- Third Party Notices.md
- Third Party Notices.md.meta
Added manifest modification API that allows editing scope registries and dependencies of the project and/or package manifest
Tested API implementation in another project.
Manifest editing example script can be provided by request
> feat: Manifest modification API

- Runtime/Utilities/ColorHelper.cs
- Runtime/Utilities/ColorHelper.cs.meta
> feat: ColorHelper

- Runtime/Utilities/Texture2DUtility.cs
- Runtime/Utilities/Texture2DUtility.cs.meta
- package.json
Texture2D Utility added
The package version is bumped to 1.0.5
> feat: Texture2DUtility

- Runtime/Utilities/RectTransformUtility.cs
- Runtime/Utilities/RectTransformUtility.cs.meta
Added RectTransformUtility class and RectTransformToScreenSpace method to it.
To have a RectTransform utility class.
No tests have been done.
> Added RectTransformUtility.

- .github/workflows/release-mods-workflow.yml
- README-RM.md
Release modifications actions
Since `The release event is not triggered for draft releases.`, it is not possible to make automatic repository modifications when creating new draft release on Website.
> feat: Release modifications actions

- Runtime/Patterns/Singleton/MonoSingleton.cs
- Runtime/Patterns/Singleton/Singleton.cs
MonoSingleton `IsDestroyed` will now actually tell if it was explicitly destroyed or not.
Also, tabs replaced with spaces.
> fix: MonoSingleton

- Runtime/Utilities/Conversion/TypeConversion.cs
- Runtime/Utilities/Conversion/TypeConversionInstance.cs
- Runtime/Utilities/Conversion/TypeConversionInstance.cs.meta
- Runtime/Utilities/Conversion/TypeConverter.cs
Add-Type Conversion alternative for safe usage in the package.
> feat: Type Conversion Instance

- Runtime/OperatingSystem/FilesBrowser.cs
> fix: FilesBrowser.OpenAtPath method. issue #60

- Runtime/Extensions/UnityEngine/SceneExtensions.cs
- Runtime/Extensions/UnityEngine/SceneExtensions.cs.meta
> feat: scene extensions.

- Runtime/Patterns/ServiceLocator.meta
- Runtime/Patterns/ServiceLocator/IReadOnlyServiceLocator.cs
- Runtime/Patterns/ServiceLocator/IReadOnlyServiceLocator.cs.meta
- Runtime/Patterns/ServiceLocator/IServiceLocator.cs
- Runtime/Patterns/ServiceLocator/IServiceLocator.cs.meta
- Runtime/Patterns/ServiceLocator/ServiceLocator.cs
- Runtime/Patterns/ServiceLocator/ServiceLocator.cs.meta
> feat: Service Locator pattern added.

- Editor/EditorUtilities/EditorWebRequest.cs
- Editor/EditorUtilities/EditorWebRequest.cs.meta
> editor web request added.

- Runtime/Extensions/UnityEngine/ComponentExtensions.cs
- Runtime/Extensions/UnityEngine/ComponentExtensions.cs.meta
- Runtime/Extensions/UnityEngine/GameObjectExtensions.cs
- Runtime/Utilities/Texture2DUtility.cs
GameObject.GetLocalIdentifierInFile  extesions method added.
> feat: GameObject.GetLocalIdentifierInFile

- Runtime/Patterns/EventBus.meta
- Runtime/Patterns/EventBus/EventBus.cs
- Runtime/Patterns/EventBus/EventBus.cs.meta
- Runtime/Patterns/EventBus/EventBusDispatcher.cs
- Runtime/Patterns/EventBus/EventBusDispatcher.cs.meta
- Runtime/Patterns/EventBus/IEvent.cs
- Runtime/Patterns/EventBus/IEvent.cs.meta
- Runtime/Patterns/EventBus/IEventBus.cs
- Runtime/Patterns/EventBus/IEventBus.cs.meta
- Runtime/Patterns/EventBus/IReadOnlyEventBus.cs
- Runtime/Patterns/EventBus/IReadOnlyEventBus.cs.meta
- Runtime/Patterns/EventBus/README.md
- Runtime/Patterns/EventBus/README.md.meta
- Runtime/Patterns/EventBus/StaticBus.cs
- Runtime/Patterns/EventBus/StaticBus.cs.meta
- Runtime/Patterns/Pooling/ObjectPool.cs
- Tests/Editor/Patterns/EventBusTests.cs
- Tests/Editor/Patterns/EventBusTests.cs.meta
Draft implementation of the simple event bus pattern.
> feat: event bus pattern

- Editor/UIToolkit/Controls/ButtonStrip/ButtonStrip.cs
- Editor/UIToolkit/Controls/ButtonStrip/ButtonStrip.uss
- Editor/UIToolkit/Controls/Hyperlink/Hyperlink.uss
> fix: fixed color scheme in light theme

- Runtime/Extensions/UnityEngine/TransformExtensions.cs
It's often used for both world and local spaces, so both of them are implemented.
No Unit tests
Tested via Unity Editor
> feat: Transform Reset method for different spaces 

- Runtime/Extensions/UnityEngine/TransformExtensions.cs
Added a couple of fancy Transform Extensions.
Please, let me know your thoughts on them.
Checked new extension methods in Editor
> feat: extended transform extensions

- Editor/EditorUtilities/EditorWebRequest.cs
- UnityRequest.downloadProgress was always 0 or 100.
- BatchMode Debug.Log(progress)
Tested 🧪 
On Merge/Release, please update Roomful Repo and poke me to implement it there.
Thanks.
> feat: Progress Bar Additions

- Runtime/Async/Coroutine/Pooled YieldInstruction/PooledYieldInstruction.cs
- Runtime/Async/Coroutine/Pooled YieldInstruction/WaitForSecondsPooled.cs
- Runtime/Async/Coroutine/Pooled YieldInstruction/WaitForSecondsRealtimePooled.cs
- Runtime/Async/Coroutine/Pooled YieldInstruction/WaitUntilPooled.cs
- Runtime/Async/Coroutine/Pooled YieldInstruction/WaitWhilePooled.cs
- Runtime/Async/Coroutine/Pooled YieldInstruction/YieldPool.cs
Implement WaitForSecondsPooled & WaitForSecondsRealtimePooled support for Unity 2019.4
* Manual tests have not performed
> feat: wait-for-seconds-unity-2019-support

- Editor/Extensions/RectExtensions.cs
- Runtime/Extensions/UnityEngine/RectTransformExtensions.cs
- Tests/Editor/Extensions/RectTransformExtensionsTest.cs
- Tests/Editor/Extensions/RectTransformExtensionsTest.cs.meta
Add new extension methods to RectTransform due to [issue](https://github.com/StansAssets/com.stansassets.foundation/issues/84).
* Includes unit tests.
All 4 methods manually tested in editor with a button with different anchors.
> feat: rect transform extensions

- Runtime/Utilities/EnumUtility.cs
- Tests/Editor/Extensions/ListExtensionsTests.cs
- Tests/Editor/Extensions/TransformExtensionsTest.cs
- Tests/Editor/Extensions/TypeExtensionsTests.cs
- Tests/Editor/Patterns/EventBusTests.cs
- Tests/Editor/Patterns/ObjectPoolTests.cs
- Tests/Editor/Utilities/EnumUtilityTests.cs
- Tests/Editor/Utilities/EnumUtilityTests.cs.meta
- Tests/Editor/Utilities/ReflectionUtilityTests.cs
Make some refactoring due to the next [issue](https://github.com/StansAssets/com.stansassets.foundation/issues/98).
Add unit tests to the EnumUtility
* Includes unit tests.
Manual tests are not required for my opinion.
> chore: enum utility refactor
